export const places = {
  towns: [
    'Hofmeyr',
    'Komani (Queenstown)',
    'Molteno',
    'Sada',
    'Sterkstroom',
    'Tarkastad',
    'Whittlesea',
    'Lady Frere',
    'Cofimvaba',
    'Dordrecht',
    'Indwe',
    'Cacadu',
    'Zwart Water',
  ],

  suburbsAndAreas: [
    'Madeira Park',
    'Top Town',
    'Komani Park',
    'Ilinge',
    'Venene',
    'Amberdale',
    'Bridge Street',
    'Nonesi Mall area',
    'Amatola',
    "Bachelor's Park",
    'Balmoral',
    'Mkhonjane',
    'Dlakavu',
    'Bolotwa',
    'Gwatyu Farms',
    'Nonibe',
    'Tylden',
    'Tembani',
    'Ilinge',
    'Mabuyaze',
    'Machibini',
    'Birch Farms',
    'Unathi Mkhefa',
    'Zone 3',
    'Zone D',
    'Chankcele',
    'Koppies',
    'McBride',
    'Who can Tell',
    'Poplar Groove',
    'Ensam',
    'Braakloof',
    'Emankcenkceni',
    'Bulhoek',
    'Kamastone',
    'Mceula',
    'Shiloh',
    'Dipala',
    'Sbonile',
    'Mbekweni',
    'Ngojini',
    'Dyamala',
    'Oxton',
    'Zweledinga',
    'Gall water',
    'Yonda',
    'Lower Hukuwa',
    'Upper Hukuwa tsitsikama',
    'Mtwakazi',
    'Zone 1',
    'Xhadini Zone',
    'Ekuphumleni',
    'Zone 2',
    'Ezibeleni',
    'Nana',
    'Phumla Mqeshi',
    'Magxaki',
    'Southbourne',
    'Westbourne',
    'Thornhill',
    'Ntabelanga',
    'Nonesi',
    'Mathyantya',
    'Ndenxe',
    'Bulhoek',
    'Qwabi',
    'Aloevale',
    'Combleigh',
    'Queensdale',
    'Nkwanca',
    'Upper Ngonyama',
  ],
};
